name: vCluster Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'vCluster version'
        required: true
        type: string
      latest:
        description: 'Push as latest'
        required: true
        default: false
        type: boolean

concurrency: 
  group: ${{ github.ref_name }}-release-${{ inputs.version }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  vcluster-release:
    strategy:
      matrix:
        arch:
        - amd64
        - ppc64le
        - s390x
        - arm64
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ vars.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: Create release
      run: docker buildx build --load --platform linux/${{ matrix.arch }} --build-arg VERSION=${{ inputs.version }} --build-arg ARCH=${{ matrix.arch }} -t ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/vcluster-pro:${{ inputs.version }}-${{ matrix.arch }} .
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
    - name: Push release
      if: ${{ ! inputs.latest }}
      run: |
        docker push --platform linux/${{ matrix.arch }} ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/vcluster-pro:${{ inputs.version }}-${{ matrix.arch }}
    - name: Push latest
      if: ${{ inputs.latest }}
      run: |
        docker tag ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/vcluster-pro:${{ inputs.version }}-${{ matrix.arch }} ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/vcluster-pro:latest
        docker push --platform linux/${{ matrix.arch }} ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/vcluster-pro:latest
  vcluster-manifest:
    needs: vcluster-release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ vars.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: Pull images
      run: |
        docker pull ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/vcluster-pro:${{ inputs.version }}-amd64
        docker pull ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/vcluster-pro:${{ inputs.version }}-ppc64le
        docker pull ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/vcluster-pro:${{ inputs.version }}-s390x
        docker pull ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/vcluster-pro:${{ inputs.version }}-arm64
    - name: Create manifest
      run: |
        docker manifest create ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/vcluster-pro:${{ inputs.latest && 'latest' || inputs.version }} \
        ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/vcluster-pro:${{ inputs.version }}-amd64 \
        ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/vcluster-pro:${{ inputs.version }}-ppc64le \
        ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/vcluster-pro:${{ inputs.version }}-s390x \
        ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/vcluster-pro:${{ inputs.version }}-arm64
    - name: Push manifest
      if: ${{ ! inputs.latest }}
      run: |
        docker manifest push ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/vcluster-pro:${{ inputs.version }}
    - name: Push latest
      if: ${{ inputs.latest }}
      run: |
        docker manifest push ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/vcluster-pro:latest
